heat_template_version: 2018-08-31

description: >
  First instance in OpenStack created by Heat!

parameters:
  RouterName:
    type: string
    label: RouterName
    description: Router name to be configured
    default: 'FirstRouter'

  ServerName:
    type: string
    label: ServerName
    description: Server name to be configured
    default: 'FirstServer'
  ServerFlavor:
    type: string
    label: ServerFlavor
    description: Server flavor to be configured
    default: 'm1.micro'
  ServerImage:
    type: string
    label: ServerImage
    description: Server image to be configured
    default: 'cirros-0.4.0-x86_64-disk'

parameter_groups:
  - label: Router
    description: All parameters related to router configuation
    parameters:
      - RouterName

  - label: Server
    description: All parameters related to server configuration
    parameters:
      - ServerName
      - ServerFlavor
      - ServerImage

resources:
  Net:
    type: OS::Neutron::Net
    properties:
      name: 'private-network'
      shared: false
  Subnet:
    type: OS::Neutron::Subnet
    properties:
      name: 'private-subnet'
      network: { get_resource: Net }
      cidr: 10.0.0.0/24
      enable_dhcp: true

  Router:
    type: OS::Neutron::Router
    properties:
      name: { get_param: RouterName }
      admin_state_up: true
      external_gateway_info:
        enable_snat: true
        network: 'public'
      tags:
        - { get_param: RouterName }
  RouterInterface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: Router }
      subnet: { get_resource: Subnet }

  Server:
    type: OS::Nova::Server
    properties:
      name: { get_param: ServerName }
      flavor: { get_param: ServerFlavor }
      image: { get_param: ServerImage }
      networks:
        - network: { get_resource: Net }
      tags:
        - { get_param: ServerName }
